### ISSUE TITLE
Not having xdg-open when attempting to open a file terminates tremc

### ISSUE THREAD

**Issue by bstaletic** [tremc/tremc#134]
First, thank you for creating `tremc`! Just what I was looking for in a transmission client. 
After hitting enter on a file in tremc I was greeted by a massive traceback of an unhandled exception.

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.13/tremc", line 2449, in view_file
    call(viewer_cmd)
    ~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 395, in call
    with Popen(*popenargs, **kwargs) as p:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/subprocess.py", line 1966, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.13/tremc", line 1412, in __init__
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python-exec/python3.13/tremc", line 1550, in run
    if self.handle_user_input() == -1:
       ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python-exec/python3.13/tremc", line 2577, in handle_user_input
    f()
    ~^^
  File "/usr/lib/python-exec/python3.13/tremc", line 2401, in action_view_file
    self.view_file(gconfig.file_viewer, gconfig.file_open_in_terminal)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python-exec/python3.13/tremc", line 2456, in view_file
    self.get_screen_size()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python-exec/python3.13/tremc", line 1466, in get_screen_size
    curses.endwin()
    ~~~~~~~~~~~~~^^
_curses.error: endwin() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.13/tremc", line 5317, in <module>
    Interface(Transmission(gconfig.url, gconfig.username, gconfig.password))
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python-exec/python3.13/tremc", line 1414, in __init__
    self.restore_screen()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python-exec/python3.13/tremc", line 1461, in restore_screen
    curses.endwin()
    ~~~~~~~~~~~~~^^
_curses.error: endwin() returned ERR
```

Not a big deal, but I thought I could just as well report this.

**Comment by AdarshI** [comment]
I too have a similar issue when closing a file I've opened from within tremc, such as a video or image, then I get a traceback identitcal to the one above starting from the second instance of `Traceback (most recent call last):` to the end. I've had this issue for some years now, but I haven't been able to find any information on it. I do have `xdg-open` installed and working though, as tremc correctly launches `mpv` with videos, for example.

**Comment by AdarshI** [comment]
@MatanZ Thanks, I no longer get this issue using your fork. Is that try catch merged into the main repo? I've used the tremc-git AUR build until now.
``

**Comment by MatanZ** [comment]
It is in 0.9.4.
