### ISSUE TITLE
Latest commit crashes with KeyError: 'reverse'

### ISSUE THREAD

**Issue by elundmark** [tremc/tremc#64]
tremc 0.9.2 with latest git commit 347b1aa

```
Traceback (most recent call last):
  File "/usr/local/bin/tremc", line 4972, in <module>
    Interface(Transmission(gconfig.url, gconfig.username, gconfig.password))
  File "/usr/local/bin/tremc", line 1242, in __init__
    self.torrents = self.server.get_torrent_list(gconfig.sort_orders)
  File "/usr/local/bin/tremc", line 832, in get_torrent_list
    self.torrent_cache.sort(key=lambda x: sort_value(x[sort_order['name']]),
  File "/usr/local/bin/tremc", line 832, in <lambda>
    self.torrent_cache.sort(key=lambda x: sort_value(x[sort_order['name']]),
KeyError: 'reverse'
```

**Comment by gangelop** [comment]
Can you please share your `settings.cfg`?

**Comment by elundmark** [comment]
I manually removed `reverse:` and now it works.

```
[Connection]
password =
username =
port = 9091
host = localhost
path = /transmission/rpc
ssl = False

[Sorting]
order = reverse:queuePosition

[Filtering]
filter =
invert = False

[Misc]
compact_list = False
torrentname_is_progressbar = False
file_viewer = /home/me/bin/silent_exo_open %%s
file_open_in_terminal = True
blank_lines = True

[Colors]
title_seed = bg:green,fg:black
title_download = bg:blue,fg:black
title_idle = bg:cyan,fg:black
title_verify = bg:magenta,fg:black
title_paused = bg:black,fg:white
title_error = bg:red,fg:white
download_rate = bg:black,fg:blue
upload_rate = bg:black,fg:red
eta+ratio = bg:black,fg:white
filter_status = bg:red,fg:black
dialog = bg:black,fg:white
dialog_important = bg:red,fg:black
button = bg:white,fg:black
button_focused = bg:black,fg:white
file_prio_high = bg:red,fg:black
file_prio_normal = bg:white,fg:black
file_prio_low = bg:yellow,fg:black
file_prio_off = bg:blue,fg:black
```

**Comment by gangelop** [comment]
ok thanks. Apparently prepending just `:` like this `order = :queuePosition` will reverse the sort order.
I glossed over this issue here https://github.com/tremc/tremc/pull/60#issuecomment-694038147. I should have tested it more.

**Comment by gangelop** [comment]
@MatanZ Might also want to take a look at this. Apparently the example you gave for sorting in 3c48d460 doesn't work.

```ini
[Sorting]
# Set startup torrent list sort order. Possible sort keys are:
#  name, addedDate, percentDone, seeders, leechers, sizeWhenDone, status, 
#  uploadedEver, rateUpload, rateDownload, uploadRatio, peersConnected, 
#  downloadDir, mainTrackerDomain.
# Append ':reverse' for reversed sort.
# Examples:
#
#  order = name:reverse 
#  Sorts by torrent name in reversed alphabetical order.
#
#  order = sizeWhenDone
#  Sorts by torrent size, small to large.
```

**Comment by elundmark** [comment]
Yes you're right, I changed it to "status" - works fine for me now. thanks!

**Comment by gangelop** [comment]
with git bisect good 347b1aa and bad 0.9.2
0794120
```
79412029f1efe4a032aff6bb8b7b2880607ff28 is the first bad commit
commit 079412029f1efe4a032aff6bb8b7b2880607ff28
Author: Matan Ziv-Av <matan@svgalib.org>
Date:   Mon Aug 17 03:05:44 2020 +0300

    Simplify setup of sort options

 tremc | 7 +++----
 1 file changed, 3 insertions(+), 4 deletions(-)
```

**Comment by gangelop** [comment]
Ok, so what's happening here is that `queuePosition` stopped being a valid sort order key and if you just do `order = queuePosition` it will be silently ignored same as `order = foobar`, which is imo an acceptable behavior. But if you do `order = reversed:Some_invalid_key` it will crash. This behavior is inconsistent and can be improved.

**Comment by gangelop** [comment]
Sorting by queue position is still possible through the interactive menu. So it should also be accepted in the config file. This is a bug.

**Comment by gangelop** [comment]
git bisect says that the first commit where `order = queuePosition` starts to be ignored is:
```
3a784e2df136fdfba1dd0c448ed797a934435230 is the first bad commit
commit 3a784e2df136fdfba1dd0c448ed797a934435230
Author: Matan Ziv-Av <matan@svgalib.org>
Date:   Mon Jun 29 20:34:25 2020 +0300

    Prevent crash on illegal filter or sort order in config file

 tremc | 33 +++++++++++++++++++--------------
 1 file changed, 19 insertions(+), 14 deletions(-)
```

**Comment by gangelop** [comment]
I've found the issue. Working on a fix...

**Comment by gangelop** [comment]
Just a status update:

This is basically the problem.

There is a check to only consider `queuePosition` if the server's rpc version is `>= 14`. But this check happens after the config is parsed so `queuePosition` is always ignored in the config. The check needs to happen after `self.sort_options` is defined and before that `config.get` reads the config file.

```python
class GConfig:
# ...
    def __init__(self):
# ...
        self.sort_options = [
            ('name', '_Name'), ('addedDate', '_Age'), ('percentDone', '_Progress'),
            ('seeders', '_Seeds'), ('leechers', 'Lee_ches'), ('sizeWhenDone', 'Si_ze'),
            ('status', 'S_tatus'), ('uploadedEver', 'Up_loaded'),
            ('rateUpload', '_Upload Speed'), ('rateDownload', '_Download Speed'),
            ('uploadRatio', '_Ratio'), ('peersConnected', 'P_eers'),
            ('downloadDir', 'L_ocation'), ('mainTrackerDomain', 'Trac_ker'),
            ('reverse', 'Re_verse')]
# ...
        self.sort_orders = parse_sort_str(config.get('Sorting', 'order', fallback=''), [x[0] for x in self.sort_options])
# ...                                     ^^^^^^^^^^                                                  ^^^^^^^^^^^^^^^^^
# ...
class Interface:
# ...
    def __init__(self, server):
# ...
        # queue was implemmented in transmission 2.4
        if self.server.get_rpc_version() >= 14:
            gconfig.sort_options.insert(-1, ('queuePosition', '_Queue Position'))
```

However, the reason we can't just cut and paste it is because "'GConfig' object has no attribute 'server'". We can't check the server rpc version because there's no connection established yet when `GConfig` is initialized.

```
Traceback (most recent call last):
  File "./tremc", line 4908, in <module>
    gconfig = GConfig()
  File "./tremc", line 194, in __init__
    if self.server.get_rpc_version() >= 14:
AttributeError: 'GConfig' object has no attribute 'server'
```

**Comment by gangelop** [comment]
One possible approach would be to include the `queuePosition` option during startup, before knowing what server we're talking to and then, after we connect, if RPC version is not `>= 14` then default to using the first valid sort option.

**Comment by MatanZ** [comment]
I guess it is possible to include it statically, and remove it in Interface.\_\_init\_\_() if necessary. Anyway, I believe it is quite unlikely for someone to run a version of transmission without queue.
