### ISSUE TITLE
Complications from #60

### ISSUE THREAD

**Issue by mohkale** [tremc/tremc#65]
Super glad #60 finally got merged. I'm loving all the new features. This issue is to collect any bugs or other problems that got through the merge.

- line 136, `connection` is misspelled as `connetion` meaning the config option for port isn't read properly.

**Comment by MatanZ** [comment]
About colors: it is my plan to have all elements configurable. This requires adding attributes to the config file colors options, and alowing a color to be defined as "the other color + some attribute", or similar.

'A' does not select all. It selects all in directory. then it jumps the next directory, to allow you to press AAA to select three directories. I guess if you are on the last directory it jumps to the last file, as that is closest to the case if not last directory.

**Comment by mohkale** [comment]
Kay, I read the docs for `A` in the torrent list and assumed it would be the same for the files view. I suppose it makes sense that it pushes you to the end of the directory then. Thnx for the clarification.

**Comment by mohkale** [comment]
I just installed tremc in a brand new machine and it crashes when transmission doesn't have any torrents.

```
Traceback (most recent call last):
  File "/usr/bin/tremc", line 4972, in <module>
    Interface(Transmission(gconfig.url, gconfig.username, gconfig.password))
  File "/usr/bin/tremc", line 1254, in __init__
    self.rateDownload_width = self.get_rateDownload_width(self.torrents)
  File "/usr/bin/tremc", line 1390, in get_rateDownload_width
    new_width = max([len(scale_bytes(x['rateDownload'])) for x in torrents])
ValueError: max() arg is an empty sequence
```

**Comment by MatanZ** [comment]
This is solved in one of the commits of PR #69 .
