### ISSUE TITLE
Crash when trying to view torrent with python 3.9

### ISSUE THREAD

**Issue by fn-ix** [tremc/tremc#90]
Hi!

After upgrading pyton to 3.9, tremc crashes when I try to view the torrent details. The error message gets garbled up with the interface, so I've included a screenshot of it: ![](https://i.imgur.com/4ZB8voB.png)

**Comment by louipc** [comment]
On Wed 21 Oct 2020 10:13 -0700, Tõnis Rand wrote:
> After upgrading pyton to 3.9, tremc crashes when I try to view the torrent
> details. The error message gets garbled up with the interface, so I've
> included a screenshot of it: ![](https://i.imgur.com/4ZB8voB.png)

You are running an old version. Please upgrade.

**Comment by fn-ix** [comment]
I'm running version 0.9.2, which seems to be the latest release.

**Comment by louipc** [comment]
On Wed 21 Oct 2020 16:07 -0700, Tõnis Rand wrote:
> I'm running version 0.9.2, which seems to be the latest release.

Sorry you are right. There hasn't been a new release yet.
You could try a git build in the meantime if its available to you.

**Comment by gangelop** [comment]
You are indeed running the latest version which is a very old version. That's our fault. Please stand by...

**Comment by pitsi** [comment]
I face the same issue since debian unstable moved to python 3.9 almost a week ago. It works as it should on debian testing which is still on python 3.8.
I am on tremc 0.9.2 and transmission 3.0.

**Comment by gangelop** [comment]
> although it has its colors messed up

screenshot please?

**Comment by pitsi** [comment]
There you go. This only happens on my terminal (urxvt, black letters, white(ish) background). On the tty everything is shown as usual

![2020-11-27-071134_896x460_scrot](https://user-images.githubusercontent.com/5880037/100428487-b2ef7100-309c-11eb-9ff6-bb4bfa4f48e1.png)
![2020-11-27-071205_896x460_scrot](https://user-images.githubusercontent.com/5880037/100428494-b4b93480-309c-11eb-8a17-9edaec302833.png)
![2020-11-27-071236_896x460_scrot](https://user-images.githubusercontent.com/5880037/100428499-b551cb00-309c-11eb-86b4-917dc3797e89.png)

I was trying out the cycle torrent line height option.

**Comment by charlie39** [comment]
edit line 441. Replace 'decodestrings' with 'decodebytes'. You are done till the next update.

![tremc1](https://user-images.githubusercontent.com/13074369/101394763-fe045200-38ee-11eb-98f4-e5e3c014525d.png)

**Comment by samyak039** [comment]
even the executable from this git repo is having error, this error even stops it from opening `tremc`.

this is the error, any fixes to this ?
```
Traceback (most recent call last):
  File "/usr/bin/tremc", line 993, in __init__
    self.init_screen()
  File "/usr/bin/tremc", line 1006, in init_screen
    curses.noecho() ; curses.cbreak() ; self.screen.keypad(1)
_curses.error: cbreak() returned ERR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/tremc", line 3728, in <module>
    Interface()
  File "/usr/bin/tremc", line 996, in __init__
    self.restore_screen()
  File "/usr/bin/tremc", line 1022, in restore_screen
    curses.endwin()
_curses.error: endwin() returned ERR
```
